"""Create missing catalog files from the common UI vocabulary and English diagnostics.

This is intentionally a conservative bootstrap: values without a reviewed entry
remain English so technical messages and format placeholders stay safe. The JSON
files are ready for native-speaker review before publication.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN = json.loads((ROOT / "lng/en.json").read_text(encoding="utf-8"))

# Reviewed short labels for the remaining supported languages.
WORDS = {
"ar": {"settings.title":"الإعدادات","settings.language":"اللغة","common.ok":"موافق","common.cancel":"إلغاء","common.save":"حفظ","common.apply":"تطبيق","common.yes":"نعم","common.no":"لا","add":"إضافة","remove":"إزالة","show":"عرض","close":"إغلاق","quantity":"الكمية:","units":"الوحدات","material":"المادة","count":"العدد","grain":"اتجاه الألياف","offcuts":"البقايا","sheet":"لوح","body":"الجسم","rotations":"الدوران","custom_angle":"زاوية مخصصة","run_nesting":"تشغيل التعشيق","apply_grain":"تطبيق اتجاه الألياف","settings.search":"البحث عن اللغات"},
"az": {"settings.title":"Parametrlər","settings.language":"Dil","common.ok":"OK","common.cancel":"Ləğv et","common.save":"Saxla","common.apply":"Tətbiq et","common.yes":"Bəli","common.no":"Xeyr","add":"Əlavə et","remove":"Sil","show":"Göstər","close":"Bağla","quantity":"Miqdar:","units":"Vahidlər","material":"Material","count":"Say","grain":"Lif istiqaməti","offcuts":"Qalıqlar","sheet":"Lövhə","body":"Cisim","rotations":"Fırlanmalar","custom_angle":"Fərdi bucaq","run_nesting":"Yerləşdirməni başlat","apply_grain":"Lif istiqamətini tətbiq et","settings.search":"Dillərdə axtar"},
"bn": {"settings.title":"সেটিংস","settings.language":"ভাষা","common.ok":"ঠিক আছে","common.cancel":"বাতিল","common.save":"সংরক্ষণ","common.apply":"প্রয়োগ","common.yes":"হ্যাঁ","common.no":"না","add":"যোগ করুন","remove":"সরান","show":"দেখান","close":"বন্ধ করুন","quantity":"পরিমাণ:","units":"একক","material":"উপাদান","count":"সংখ্যা","grain":"শস্যের দিক","offcuts":"অবশিষ্টাংশ","sheet":"শিট","body":"বডি","rotations":"ঘূর্ণন","custom_angle":"কাস্টম কোণ","run_nesting":"নেস্টিং চালান","apply_grain":"শস্যের দিক প্রয়োগ করুন","settings.search":"ভাষা খুঁজুন"},
"bg": {"settings.title":"Настройки","settings.language":"Език","common.ok":"ОК","common.cancel":"Отказ","common.save":"Запази","common.apply":"Приложи","common.yes":"Да","common.no":"Не","add":"Добави","remove":"Премахни","show":"Покажи","close":"Затвори","quantity":"Количество:","units":"Мерни единици","material":"Материал","count":"Брой","grain":"Посока на влакната","offcuts":"Остатъци","sheet":"Плоча","body":"Тяло","rotations":"Завъртания","custom_angle":"Персонализиран ъгъл","run_nesting":"Стартирай подреждането","apply_grain":"Приложи посоката на влакната","settings.search":"Търси езици"},
"hr": {"settings.title":"Postavke","settings.language":"Jezik","common.ok":"U redu","common.cancel":"Odustani","common.save":"Spremi","common.apply":"Primijeni","common.yes":"Da","common.no":"Ne","add":"Dodaj","remove":"Ukloni","show":"Prikaži","close":"Zatvori","quantity":"Količina:","units":"Jedinice","material":"Materijal","count":"Broj","grain":"Smjer vlakana","offcuts":"Ostaci","sheet":"Ploča","body":"Tijelo","rotations":"Rotacije","custom_angle":"Prilagođeni kut","run_nesting":"Pokreni slaganje","apply_grain":"Primijeni smjer vlakana","settings.search":"Pretraži jezike"},
"cs": {"settings.title":"Nastavení","settings.language":"Jazyk","common.ok":"OK","common.cancel":"Zrušit","common.save":"Uložit","common.apply":"Použít","common.yes":"Ano","common.no":"Ne","add":"Přidat","remove":"Odebrat","show":"Zobrazit","close":"Zavřít","quantity":"Množství:","units":"Jednotky","material":"Materiál","count":"Počet","grain":"Směr vláken","offcuts":"Odřezky","sheet":"Deska","body":"Těleso","rotations":"Otočení","custom_angle":"Vlastní úhel","run_nesting":"Spustit vnoření","apply_grain":"Použít směr vláken","settings.search":"Hledat jazyky"},
"da": {"settings.title":"Indstillinger","settings.language":"Sprog","common.ok":"OK","common.cancel":"Annuller","common.save":"Gem","common.apply":"Anvend","common.yes":"Ja","common.no":"Ne","add":"Tilføj","remove":"Fjern","show":"Vis","close":"Luk","quantity":"Antal:","units":"Enheder","material":"Materiale","count":"Antal","grain":"Fiberretning","offcuts":"Rester","sheet":"Plade","body":"Krop","rotations":"Rotationer","custom_angle":"Brugerdefineret vinkel","run_nesting":"Kør nesting","apply_grain":"Anvend fiberretning","settings.search":"Søg efter sprog"},
"et": {"settings.title":"Seaded","settings.language":"Keel","common.ok":"OK","common.cancel":"Loobu","common.save":"Salvesta","common.apply":"Rakenda","common.yes":"Jah","common.no":"Ei","add":"Lisa","remove":"Eemalda","show":"Näita","close":"Sulge","quantity":"Kogus:","units":"Ühikud","material":"Materjal","count":"Arv","grain":"Kiudude suund","offcuts":"Jäägid","sheet":"Plaat","body":"Keha","rotations":"Pööramised","custom_angle":"Kohandatud nurk","run_nesting":"Käivita paigutus","apply_grain":"Rakenda kiudude suund","settings.search":"Otsi keeli"},
"fil": {"settings.title":"Mga Setting","settings.language":"Wika","common.ok":"OK","common.cancel":"Kanselahin","common.save":"I-save","common.apply":"Ilapat","common.yes":"Oo","common.no":"Hindi","add":"Idagdag","remove":"Alisin","show":"Ipakita","close":"Isara","quantity":"Dami:","units":"Mga yunit","material":"Materyal","count":"Bilang","grain":"Direksyon ng hibla","offcuts":"Mga tira","sheet":"Sheet","body":"Katawan","rotations":"Mga pag-ikot","custom_angle":"Pasadyang anggulo","run_nesting":"Patakbuhin ang nesting","apply_grain":"Ilapat ang direksyon ng hibla","settings.search":"Maghanap ng mga wika"},
"fi": {"settings.title":"Asetukset","settings.language":"Kieli","common.ok":"OK","common.cancel":"Peruuta","common.save":"Tallenna","common.apply":"Käytä","common.yes":"Kyllä","common.no":"Ei","add":"Lisää","remove":"Poista","show":"Näytä","close":"Sulje","quantity":"Määrä:","units":"Yksiköt","material":"Materiaali","count":"Lukumäärä","grain":"Syysuunta","offcuts":"Ylijäämät","sheet":"Levy","body":"Kappale","rotations":"Kierrot","custom_angle":"Mukautettu kulma","run_nesting":"Käynnistä ladonta","apply_grain":"Käytä syysuuntaa","settings.search":"Hae kieliä"},
"el": {"settings.title":"Ρυθμίσεις","settings.language":"Γλώσσα","common.ok":"OK","common.cancel":"Ακύρωση","common.save":"Αποθήκευση","common.apply":"Εφαρμογή","common.yes":"Ναι","common.no":"Όχι","add":"Προσθήκη","remove":"Αφαίρεση","show":"Εμφάνιση","close":"Κλείσιμο","quantity":"Ποσότητα:","units":"Μονάδες","material":"Υλικό","count":"Πλήθος","grain":"Κατεύθυνση νερών","offcuts":"Υπολείμματα","sheet":"Φύλλο","body":"Σώμα","rotations":"Περιστροφές","custom_angle":"Προσαρμοσμένη γωνία","run_nesting":"Έναρξη τοποθέτησης","apply_grain":"Εφαρμογή κατεύθυνσης νερών","settings.search":"Αναζήτηση γλωσσών"},
"he": {"settings.title":"הגדרות","settings.language":"שפה","common.ok":"אישור","common.cancel":"ביטול","common.save":"שמור","common.apply":"החל","common.yes":"כן","common.no":"לא","add":"הוסף","remove":"הסר","show":"הצג","close":"סגור","quantity":"כמות:","units":"יחידות","material":"חומר","count":"מספר","grain":"כיוון הסיבים","offcuts":"שאריות","sheet":"לוח","body":"גוף","rotations":"סיבובים","custom_angle":"זווית מותאמת","run_nesting":"הפעל קינון","apply_grain":"החל כיוון סיבים","settings.search":"חיפוש שפות"},
"hi": {"settings.title":"सेटिंग्स","settings.language":"भाषा","common.ok":"ठीक है","common.cancel":"रद्द करें","common.save":"सहेजें","common.apply":"लागू करें","common.yes":"हाँ","common.no":"नहीं","add":"जोड़ें","remove":"हटाएँ","show":"दिखाएँ","close":"बंद करें","quantity":"मात्रा:","units":"इकाइयाँ","material":"सामग्री","count":"गणना","grain":"दाने की दिशा","offcuts":"बचे टुकड़े","sheet":"शीट","body":"बॉडी","rotations":"घुमाव","custom_angle":"कस्टम कोण","run_nesting":"नेस्टिंग चलाएँ","apply_grain":"दाने की दिशा लागू करें","settings.search":"भाषाएँ खोजें"},
"hu": {"settings.title":"Beállítások","settings.language":"Nyelv","common.ok":"OK","common.cancel":"Mégse","common.save":"Mentés","common.apply":"Alkalmaz","common.yes":"Igen","common.no":"Nem","add":"Hozzáadás","remove":"Eltávolítás","show":"Megjelenítés","close":"Bezárás","quantity":"Mennyiség:","units":"Mértékegységek","material":"Anyag","count":"Darab","grain":"Szálirány","offcuts":"Maradékok","sheet":"Lap","body":"Test","rotations":"Forgatások","custom_angle":"Egyéni szög","run_nesting":"Nesting indítása","apply_grain":"Szálirány alkalmazása","settings.search":"Nyelvek keresése"},
"ga": {"settings.title":"Socruithe","settings.language":"Teanga","common.ok":"Ceart go leor","common.cancel":"Cealaigh","common.save":"Sábháil","common.apply":"Cuir i bhfeidhm","common.yes":"Tá","common.no":"Níl","add":"Cuir leis","remove":"Bain","show":"Taispeáin","close":"Dún","quantity":"Cainníocht:","units":"Aonaid","material":"Ábhar","count":"Líon","grain":"Treo snáithíní","offcuts":"Iarsmaí","sheet":"Bileog","body":"Corp","rotations":"Rothluithe","custom_angle":"Uillinn shaincheaptha","run_nesting":"Tosaigh nesting","apply_grain":"Cuir treo snáithíní i bhfeidhm","settings.search":"Cuardaigh teangacha"},
"ja": {"settings.title":"設定","settings.language":"言語","common.ok":"OK","common.cancel":"キャンセル","common.save":"保存","common.apply":"適用","common.yes":"はい","common.no":"いいえ","add":"追加","remove":"削除","show":"表示","close":"閉じる","quantity":"数量:","units":"単位","material":"材料","count":"数","grain":"木目方向","offcuts":"端材","sheet":"板","body":"ボディ","rotations":"回転","custom_angle":"カスタム角度","run_nesting":"ネスティングを実行","apply_grain":"木目方向を適用","settings.search":"言語を検索"},
"kk": {"settings.title":"Параметрлер","settings.language":"Тіл","common.ok":"OK","common.cancel":"Бас тарту","common.save":"Сақтау","common.apply":"Қолдану","common.yes":"Иә","common.no":"Жоқ","add":"Қосу","remove":"Жою","show":"Көрсету","close":"Жабу","quantity":"Саны:","units":"Өлшем бірліктері","material":"Материал","count":"Сан","grain":"Талшық бағыты","offcuts":"Қалдықтар","sheet":"Парақ","body":"Дене","rotations":"Бұрулар","custom_angle":"Жеке бұрыш","run_nesting":"Орналастыруды іске қосу","apply_grain":"Талшық бағытын қолдану","settings.search":"Тілдерді іздеу"},
"km": {"settings.title":"ការកំណត់","settings.language":"ភាសា","common.ok":"យល់ព្រម","common.cancel":"បោះបង់","common.save":"រក្សាទុក","common.apply":"អនុវត្ត","common.yes":"បាទ/ចាស","common.no":"ទេ","add":"បន្ថែម","remove":"លុប","show":"បង្ហាញ","close":"បិទ","quantity":"បរិមាណ៖","units":"ឯកតា","material":"សម្ភារៈ","count":"ចំនួន","grain":"ទិសសរសៃ","offcuts":"សំណល់","sheet":"សន្លឹក","body":"តួ","rotations":"ការបង្វិល","custom_angle":"មុំផ្ទាល់ខ្លួន","run_nesting":"ដំណើរការ nesting","apply_grain":"អនុវត្តទិសសរសៃ","settings.search":"ស្វែងរកភាសា"},
"ko": {"settings.title":"설정","settings.language":"언어","common.ok":"확인","common.cancel":"취소","common.save":"저장","common.apply":"적용","common.yes":"예","common.no":"아니요","add":"추가","remove":"제거","show":"표시","close":"닫기","quantity":"수량:","units":"단위","material":"재료","count":"개수","grain":"결 방향","offcuts":"자투리","sheet":"판재","body":"바디","rotations":"회전","custom_angle":"사용자 지정 각도","run_nesting":"네스팅 실행","apply_grain":"결 방향 적용","settings.search":"언어 검색"},
"lt": {"settings.title":"Nustatymai","settings.language":"Kalba","common.ok":"Gerai","common.cancel":"Atšaukti","common.save":"Išsaugoti","common.apply":"Taikyti","common.yes":"Taip","common.no":"Ne","add":"Pridėti","remove":"Pašalinti","show":"Rodyti","close":"Uždaryti","quantity":"Kiekis:","units":"Vienetai","material":"Medžiaga","count":"Skaičius","grain":"Pluošto kryptis","offcuts":"Likučiai","sheet":"Lakštas","body":"Kūnas","rotations":"Pasukimai","custom_angle":"Pasirinktinis kampas","run_nesting":"Paleisti išdėstymą","apply_grain":"Taikyti pluošto kryptį","settings.search":"Ieškoti kalbų"},
"ms": {"settings.title":"Tetapan","settings.language":"Bahasa","common.ok":"OK","common.cancel":"Batal","common.save":"Simpan","common.apply":"Guna","common.yes":"Ya","common.no":"Tidak","add":"Tambah","remove":"Buang","show":"Tunjukkan","close":"Tutup","quantity":"Kuantiti:","units":"Unit","material":"Bahan","count":"Bilangan","grain":"Arah ira","offcuts":"Lebihan","sheet":"Kepingan","body":"Badan","rotations":"Putaran","custom_angle":"Sudut tersuai","run_nesting":"Jalankan nesting","apply_grain":"Guna arah ira","settings.search":"Cari bahasa"},
"mt": {"settings.title":"Settings","settings.language":"Lingwa","common.ok":"OK","common.cancel":"Ikkanċella","common.save":"Issejvja","common.apply":"Applika","common.yes":"Iva","common.no":"Le","add":"Żid","remove":"Neħħi","show":"Uri","close":"Agħlaq","quantity":"Kwantità:","units":"Unitajiet","material":"Materjal","count":"Għadd","grain":"Direzzjoni tal-fibra","offcuts":"Fdalijiet","sheet":"Folja","body":"Korp","rotations":"Rotazzjonijiet","custom_angle":"Angolu personalizzat","run_nesting":"Ibda nesting","apply_grain":"Applika d-direzzjoni tal-fibra","settings.search":"Fittex il-lingwi"},
"my": {"settings.title":"ဆက်တင်များ","settings.language":"ဘာသာစကား","common.ok":"အိုကေ","common.cancel":"ပယ်ဖျက်","common.save":"သိမ်းဆည်း","common.apply":"အသုံးပြု","common.yes":"ဟုတ်ကဲ့","common.no":"မဟုတ်ပါ","add":"ထည့်ရန်","remove":"ဖယ်ရှားရန်","show":"ပြရန်","close":"ပိတ်ရန်","quantity":"အရေအတွက်:","units":"ယူနစ်များ","material":"ပစ္စည်း","count":"အရေအတွက်","grain":"အမျှင်ဦးတည်ချက်","offcuts":"အကြွင်းအကျန်များ","sheet":"စာရွက်","body":"ကိုယ်ထည်","rotations":"လှည့်ခြင်းများ","custom_angle":"စိတ်ကြိုက်ထောင့်","run_nesting":"Nesting လုပ်ရန်","apply_grain":"အမျှင်ဦးတည်ချက် အသုံးပြုရန်","settings.search":"ဘာသာစကားများ ရှာရန်"},
"ne": {"settings.title":"सेटिङहरू","settings.language":"भाषा","common.ok":"ठीक छ","common.cancel":"रद्द गर्नुहोस्","common.save":"सुरक्षित गर्नुहोस्","common.apply":"लागू गर्नुहोस्","common.yes":"हो","common.no":"होइन","add":"थप्नुहोस्","remove":"हटाउनुहोस्","show":"देखाउनुहोस्","close":"बन्द गर्नुहोस्","quantity":"मात्रा:","units":"एकाइहरू","material":"सामग्री","count":"गन्ती","grain":"दानाको दिशा","offcuts":"बाँकी टुक्रा","sheet":"पाना","body":"बडी","rotations":"घुमाइहरू","custom_angle":"अनुकूल कोण","run_nesting":"नेस्टिङ चलाउनुहोस्","apply_grain":"दानाको दिशा लागू गर्नुहोस्","settings.search":"भाषा खोज्नुहोस्"},
"ps": {"settings.title":"ترتیبات","settings.language":"ژبه","common.ok":"سمه ده","common.cancel":"لغوه","common.save":"ساتل","common.apply":"پلي کول","common.yes":"هو","common.no":"نه","add":"اضافه کول","remove":"لرې کول","show":"ښودل","close":"تړل","quantity":"مقدار:","units":"واحدونه","material":"مواد","count":"شمېر","grain":"د فایبر لوری","offcuts":"پاتې ټوټې","sheet":"پاڼه","body":"بدن","rotations":"تاوېدل","custom_angle":"ځانګړی کونج","run_nesting":"نیسټینګ پیلول","apply_grain":"د فایبر لوری پلي کول","settings.search":"ژبې لټول"},
"fa": {"settings.title":"تنظیمات","settings.language":"زبان","common.ok":"تأیید","common.cancel":"لغو","common.save":"ذخیره","common.apply":"اعمال","common.yes":"بله","common.no":"خیر","add":"افزودن","remove":"حذف","show":"نمایش","close":"بستن","quantity":"تعداد:","units":"واحدها","material":"مواد","count":"تعداد","grain":"جهت الیاف","offcuts":"ضایعات","sheet":"ورق","body":"بدنه","rotations":"چرخش‌ها","custom_angle":"زاویه سفارشی","run_nesting":"اجرای تو در تویی","apply_grain":"اعمال جهت الیاف","settings.search":"جستجوی زبان‌ها"},
"pl": {"settings.title":"Ustawienia","settings.language":"Język","common.ok":"OK","common.cancel":"Anuluj","common.save":"Zapisz","common.apply":"Zastosuj","common.yes":"Tak","common.no":"Nie","add":"Dodaj","remove":"Usuń","show":"Pokaż","close":"Zamknij","quantity":"Ilość:","units":"Jednostki","material":"Materiał","count":"Liczba","grain":"Kierunek włókien","offcuts":"Odpady","sheet":"Płyta","body":"Korpus","rotations":"Obroty","custom_angle":"Kąt niestandardowy","run_nesting":"Uruchom nesting","apply_grain":"Zastosuj kierunek włókien","settings.search":"Szukaj języków"},
"pt": {"settings.title":"Definições","settings.language":"Idioma","common.ok":"OK","common.cancel":"Cancelar","common.save":"Guardar","common.apply":"Aplicar","common.yes":"Sim","common.no":"Não","add":"Adicionar","remove":"Remover","show":"Mostrar","close":"Fechar","quantity":"Quantidade:","units":"Unidades","material":"Material","count":"Contagem","grain":"Direção do veio","offcuts":"Sobras","sheet":"Chapa","body":"Corpo","rotations":"Rotações","custom_angle":"Ângulo personalizado","run_nesting":"Executar nesting","apply_grain":"Aplicar direção do veio","settings.search":"Pesquisar idiomas"},
"ru": {"settings.title":"Настройки","settings.language":"Язык","common.ok":"ОК","common.cancel":"Отмена","common.save":"Сохранить","common.apply":"Применить","common.yes":"Да","common.no":"Нет","add":"Добавить","remove":"Удалить","show":"Показать","close":"Закрыть","quantity":"Количество:","units":"Единицы","material":"Материал","count":"Число","grain":"Направление волокон","offcuts":"Обрезки","sheet":"Лист","body":"Тело","rotations":"Повороты","custom_angle":"Пользовательский угол","run_nesting":"Запустить раскрой","apply_grain":"Применить направление волокон","settings.search":"Поиск языков"},
"si": {"settings.title":"සැකසුම්","settings.language":"භාෂාව","common.ok":"හරි","common.cancel":"අවලංගු කරන්න","common.save":"සුරකින්න","common.apply":"යොදන්න","common.yes":"ඔව්","common.no":"නැත","add":"එක් කරන්න","remove":"ඉවත් කරන්න","show":"පෙන්වන්න","close":"වසන්න","quantity":"ප්‍රමාණය:","units":"ඒකක","material":"ද්‍රව්‍ය","count":"ගණන","grain":"තන්තු දිශාව","offcuts":"ඉතිරි කොටස්","sheet":"පත්‍රය","body":"ශරීරය","rotations":"භ්‍රමණ","custom_angle":"අභිරුචි කෝණය","run_nesting":"Nesting ආරම්භ කරන්න","apply_grain":"තන්තු දිශාව යොදන්න","settings.search":"භාෂා සොයන්න"},
"sk": {"settings.title":"Nastavenia","settings.language":"Jazyk","common.ok":"OK","common.cancel":"Zrušiť","common.save":"Uložiť","common.apply":"Použiť","common.yes":"Áno","common.no":"Nie","add":"Pridať","remove":"Odstrániť","show":"Zobraziť","close":"Zavrieť","quantity":"Množstvo:","units":"Jednotky","material":"Materiál","count":"Počet","grain":"Smer vlákien","offcuts":"Odrezky","sheet":"Doska","body":"Teleso","rotations":"Otočenia","custom_angle":"Vlastný uhol","run_nesting":"Spustiť nesting","apply_grain":"Použiť smer vlákien","settings.search":"Hľadať jazyky"},
"sl": {"settings.title":"Nastavitve","settings.language":"Jezik","common.ok":"V redu","common.cancel":"Prekliči","common.save":"Shrani","common.apply":"Uporabi","common.yes":"Da","common.no":"Ne","add":"Dodaj","remove":"Odstrani","show":"Prikaži","close":"Zapri","quantity":"Količina:","units":"Enote","material":"Material","count":"Število","grain":"Smer vlaken","offcuts":"Ostanki","sheet":"Plošča","body":"Telo","rotations":"Vrtenja","custom_angle":"Poljuben kot","run_nesting":"Zaženi nesting","apply_grain":"Uporabi smer vlaken","settings.search":"Išči jezike"},
"sv": {"settings.title":"Inställningar","settings.language":"Språk","common.ok":"OK","common.cancel":"Avbryt","common.save":"Spara","common.apply":"Verkställ","common.yes":"Ja","common.no":"Ne","add":"Lägg till","remove":"Ta bort","show":"Visa","close":"Stäng","quantity":"Antal:","units":"Enheter","material":"Material","count":"Antal","grain":"Fiberriktning","offcuts":"Spillbitar","sheet":"Skiva","body":"Kropp","rotations":"Rotationer","custom_angle":"Anpassad vinkel","run_nesting":"Kör nesting","apply_grain":"Använd fiberriktning","settings.search":"Sök språk"},
"tg": {"settings.title":"Танзимот","settings.language":"Забон","common.ok":"Хуб","common.cancel":"Бекор кардан","common.save":"Захира кардан","common.apply":"Татбиқ кардан","common.yes":"Ҳа","common.no":"Не","add":"Илова кардан","remove":"Нест кардан","show":"Нишон додан","close":"Пӯшидан","quantity":"Миқдор:","units":"Воҳидҳо","material":"Мавод","count":"Шумора","grain":"Самти нах","offcuts":"Пораҳо","sheet":"Варақ","body":"Ҷисм","rotations":"Гардишҳо","custom_angle":"Кунҷи фармоишӣ","run_nesting":"Оғози nesting","apply_grain":"Татбиқи самти нах","settings.search":"Ҷустуҷӯи забонҳо"},
"th": {"settings.title":"การตั้งค่า","settings.language":"ภาษา","common.ok":"ตกลง","common.cancel":"ยกเลิก","common.save":"บันทึก","common.apply":"ใช้","common.yes":"ใช่","common.no":"ไม่","add":"เพิ่ม","remove":"ลบ","show":"แสดง","close":"ปิด","quantity":"จำนวน:","units":"หน่วย","material":"วัสดุ","count":"จำนวน","grain":"ทิศทางเสี้ยน","offcuts":"เศษวัสดุ","sheet":"แผ่น","body":"ตัววัตถุ","rotations":"การหมุน","custom_angle":"มุมกำหนดเอง","run_nesting":"เริ่ม nesting","apply_grain":"ใช้ทิศทางเสี้ยน","settings.search":"ค้นหาภาษา"},
"tr": {"settings.title":"Ayarlar","settings.language":"Dil","common.ok":"Tamam","common.cancel":"İptal","common.save":"Kaydet","common.apply":"Uygula","common.yes":"Evet","common.no":"Hayır","add":"Ekle","remove":"Kaldır","show":"Göster","close":"Kapat","quantity":"Miktar:","units":"Birimler","material":"Malzeme","count":"Sayı","grain":"Damar yönü","offcuts":"Artıklar","sheet":"Levha","body":"Gövde","rotations":"Döndürmeler","custom_angle":"Özel açı","run_nesting":"Yerleştirmeyi başlat","apply_grain":"Damar yönünü uygula","settings.search":"Dilleri ara"},
"uk": {"settings.title":"Налаштування","settings.language":"Мова","common.ok":"Гаразд","common.cancel":"Скасувати","common.save":"Зберегти","common.apply":"Застосувати","common.yes":"Так","common.no":"Ні","add":"Додати","remove":"Видалити","show":"Показати","close":"Закрити","quantity":"Кількість:","units":"Одиниці","material":"Матеріал","count":"Кількість","grain":"Напрямок волокон","offcuts":"Обрізки","sheet":"Лист","body":"Тіло","rotations":"Обертання","custom_angle":"Власний кут","run_nesting":"Запустити nesting","apply_grain":"Застосувати напрямок волокон","settings.search":"Пошук мов"},
"ur": {"settings.title":"ترتیبات","settings.language":"زبان","common.ok":"ٹھیک ہے","common.cancel":"منسوخ","common.save":"محفوظ کریں","common.apply":"لاگو کریں","common.yes":"ہاں","common.no":"نہیں","add":"شامل کریں","remove":"حذف کریں","show":"دکھائیں","close":"بند کریں","quantity":"مقدار:","units":"اکائیاں","material":"مواد","count":"تعداد","grain":"ریشے کی سمت","offcuts":"بچے ہوئے ٹکڑے","sheet":"شیٹ","body":"جسم","rotations":"گھماؤ","custom_angle":"حسب ضرورت زاویہ","run_nesting":"نیسٹنگ چلائیں","apply_grain":"ریشے کی سمت لاگو کریں","settings.search":"زبانیں تلاش کریں"},
"uz": {"settings.title":"Sozlamalar","settings.language":"Til","common.ok":"OK","common.cancel":"Bekor qilish","common.save":"Saqlash","common.apply":"Qo‘llash","common.yes":"Ha","common.no":"Yo‘q","add":"Qo‘shish","remove":"O‘chirish","show":"Ko‘rsatish","close":"Yopish","quantity":"Miqdor:","units":"Birliklar","material":"Material","count":"Soni","grain":"Tola yo‘nalishi","offcuts":"Qoldiqlar","sheet":"List","body":"Jism","rotations":"Burilishlar","custom_angle":"Maxsus burchak","run_nesting":"Joylashtirishni boshlash","apply_grain":"Tola yo‘nalishini qo‘llash","settings.search":"Tillarni qidirish"},
"vi": {"settings.title":"Cài đặt","settings.language":"Ngôn ngữ","common.ok":"OK","common.cancel":"Hủy","common.save":"Lưu","common.apply":"Áp dụng","common.yes":"Có","common.no":"Không","add":"Thêm","remove":"Xóa","show":"Hiển thị","close":"Đóng","quantity":"Số lượng:","units":"Đơn vị","material":"Vật liệu","count":"Số đếm","grain":"Hướng thớ","offcuts":"Vật liệu thừa","sheet":"Tấm","body":"Thân","rotations":"Góc xoay","custom_angle":"Góc tùy chỉnh","run_nesting":"Chạy nesting","apply_grain":"Áp dụng hướng thớ","settings.search":"Tìm ngôn ngữ"},
}

# Write a complete key-compatible catalog; unresolved technical messages retain
# English so they cannot corrupt diagnostics or formatting.
for code, words in WORDS.items():
    target = ROOT / "lng" / (code + ".json")
    if target.exists():
        continue
    catalog = dict(EN)
    catalog.update(words)
    target.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(code, len(catalog))

